version: '3.8'

services:
  frontend:
    image: frontend:latest
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: backend:latest
    build:
      context: ./backend
    ports:
      - "8000:8000"
